<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright since 2026 Mifos Initiative

 This Source Code Form is subject to the terms of the Mozilla Public
 License, v. 2.0. If a copy of the MPL was not distributed with this
 file, You can obtain one at http://mozilla.org/MPL/2.0/. 
-->
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.14</version>
		<relativePath/>
	</parent>
	<groupId>community.mifos</groupId>
	<artifactId>birt-plugin</artifactId>
	<version>1.15.0-SNAPSHOT</version>
	<name>birt-plugin</name>
	<description>Mifos BIRT Reporting Plugin for Apache Fineract</description>
	<properties>
		<java.version>21</java.version>
		<fineract.version>0.0.1372-1fe5c08</fineract.version>
		<eclipselink.version>4.0.9</eclipselink.version>
		<birt.version>4.23.0</birt.version>
		<icu4j.version>78.3</icu4j.version>
                <csv.emitter.version>1.0.11</csv.emitter.version>
		<spotless.version>3.5.1</spotless.version>
		<google-java-format.version>1.17.0</google-java-format.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
			<version>${icu4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
                <dependency>
                    <groupId>org.liquibase</groupId>
                    <artifactId>liquibase-core</artifactId>
                    <scope>compile</scope>
                </dependency>
		<dependency>
			<groupId>jakarta.ws.rs</groupId>
			<artifactId>jakarta.ws.rs-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>eclipselink</artifactId>
			<version>${eclipselink.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.fineract</groupId>
			<artifactId>fineract-provider</artifactId>
			<version>${fineract.version}</version>
			<classifier>plain</classifier>
			<exclusions>
				<exclusion>
					<groupId>org.apache.fineract</groupId>
					<artifactId>fineract-avro-schemas</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.fineract</groupId>
			<artifactId>fineract-client</artifactId>
			<version>0.0.1378-f94fc33</version>
		</dependency>
		<dependency>
			<groupId>org.apache.fineract</groupId>
			<artifactId>fineract-core</artifactId>
			<version>${fineract.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.fineract</groupId>
			<artifactId>fineract-report</artifactId>
			<version>${fineract.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.fineract</groupId>
			<artifactId>fineract-security</artifactId>
			<version>${fineract.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.core</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.model</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.fonts</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.data</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.data.oda.jdbc</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.chart.engine</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.core.script.function</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.script.javascript</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.data.aggregation</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.data.adapter</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.chart.reportitem</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.dataextraction</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.pdf</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.config.pdf</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.html</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.config.html</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>uk.co.spudsoft.birt.emitters.excel</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.prototype.excel</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.config.excel</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt</groupId>
			<artifactId>org.eclipse.birt.report.engine.dataextraction.csv</artifactId>
			<version>${birt.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.jamestoney311</groupId>
			<artifactId>org.eclipse.birt.report.engine.emitter.csv</artifactId>
			<version>${csv.emitter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		             
                <dependency>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                    <scope>compile</scope>
                </dependency>
	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
				<plugin>
					<groupId>com.diffplug.spotless</groupId>
					<artifactId>spotless-maven-plugin</artifactId>
					<version>${spotless.version}</version>
					<configuration>
						<java>
							<googleJavaFormat>
								<version>${google-java-format.version}</version>
								<style>GOOGLE</style>
							</googleJavaFormat>
							<importOrder />
							<removeUnusedImports />
						</java>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>check</goal>
							</goals>
							<phase>compile</phase>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<repositories>
		<repository>
			<id>fineract-release</id>
			<name>libs-release-local</name>
			<url>https://mifos.jfrog.io/artifactory/libs-release</url>
		</repository>
		<repository>
			<id>fineract-snapshot</id>
			<name>libs-snapshot-local</name>
			<url>https://mifos.jfrog.io/artifactory/libs-snapshot</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>oss-sonatype</id>
			<name>oss-sonatype</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
		<pluginRepository>
			<id>release</id>
			<name>libs-release-local</name>
			<url>https://mifos.jfrog.io/artifactory/libs-release-local</url>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<repository>
			<id>central</id>
			<name>Mifos Artifactory</name>
			<url>https://mifos.jfrog.io/artifactory/libs-snapshot-local/</url>
		</repository>
	</distributionManagement>
</project>

